version: '3'
services:
  # Backend prediction fast API
  backendprediction:
    build: ./src/backend_prediction
    container_name: backendprediction
    ports:
      - "80:80"
    networks:
      - fe_be_network
    volumes:
      - ./model:/model
    command: python -m main_backend_prediction

  frontendprediction:
    build: ./src/frontend_prediction
    container_name: frontendprediction
    depends_on:
      - backendprediction
    ports:
      - "8501:8501"
    networks:
      - fe_be_network
    environment:
      - HOST_B=backendprediction
      - PORT_B=80
    command: streamlit run main_frontend_prediction.py

networks:
  fe_be_network:
    driver: bridge
