version: '3'
services:
  # Backend prediction fast API
  backendprediction:
    build: ./src/backend_prediction
    container_name: backendprediction
    depends_on:
      - brokerkafka
    ports:
      - "80:80"
    networks:
      - fe_be_network
      - kafka_network
    environment:
      - SERVERS_K=brokerkafka:29092
      - TOPIC_SUCCESS=prediction_sucess
      - TOPIC_ERROR=prediction_error
    volumes:
      - ./model:/model
    command: python -m main_backend_prediction

  # Frontend prediction Streamlit
  frontendprediction:
    build: ./src/frontend_prediction
    container_name: frontendprediction
    depends_on:
      - backendprediction
    ports:
      - "8501:8501"
    networks:
      - fe_be_network
    environment:
      - HOST_B=backendprediction
      - PORT_B=80
    command: streamlit run main_frontend_prediction.py

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    networks:
      - zoo_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  brokerkafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: brokerkafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - kafka_network
      - zoo_network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://brokerkafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

networks:
  fe_be_network:
    driver: bridge
  
  kafka_network:
    driver: bridge
  
  zoo_network:
    driver: bridge

